name: Deploy techtop to Dev2

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deploy files
      id: deploy
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{secrets.SSH_GITHUB_ACTIONS_PEM}}
      with:
        flags: '-avzr --delete'
        options: ''
        ssh_options: '-p 22'
        src: ''
        dest: 'root@45.12.19.95:/var/www/test1.monolitpro.info/www'
